spring:
  application:
    name: object
  threads:
    virtual:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/jpa
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
